import alabanza1Raw from '../alabanza1.html?raw';
import alabanza61Raw from '../alabanza61.html?raw';
import alabanza62Raw from '../alabanza62.html?raw';
import alabanza63Raw from '../alabanza63.html?raw';
import alabanza64Raw from '../alabanza64.html?raw';
import alabanza65Raw from '../alabanza65.html?raw';
import alabanza66Raw from '../alabanza66.html?raw';
import alabanza67Raw from '../alabanza67.html?raw';

export const categories = [
  {
    id: 'adoracion',
    name: 'Adoración',
    description: 'Cantos para entrar en la presencia de Dios',
    hymns: [
      { id: 'alabanza1', title: 'AL CORDERO DAD (ALELUYA)', source: alabanza1Raw },
      { id: 'alabanza2', title: 'ALELUYA (GLORIA ALELUYA)' },
      { id: 'alabanza3', title: 'ALGO ESTA CAYENDO AQUI' },
      { id: 'alabanza4', title: 'MILAGROSO ABRES CAMINOS' },
      { id: 'alabanza5', title: 'AMARTE MAS' },
      { id: 'alabanza6', title: 'AL ESTAR AQUI (AL ESTAR EN TU PRESENCIA)' },
      { id: 'alabanza7', title: 'A TUS PIES' },
      { id: 'alabanza8', title: 'AMARTE SOLO A TI' },
      { id: 'alabanza9', title: 'A PESAR DE MI INFIDELIDAD' },
      { id: 'alabanza10', title: 'ATRAEME A TI' },
      { id: 'alabanza11', title: 'ENTRA EN LA PRESENCIA DEL SEÑOR' },
      { id: 'alabanza12', title: 'BENDECIRE A JEHOVA EN TODO TIEMPO (SALMOS 34)' },
      { id: 'alabanza13', title: 'CUANDO EL SEÑOR ME ALLO' },
      { id: 'alabanza14', title: 'CRISTO REY VICTORIOSO' },
      { id: 'alabanza15', title: 'BODAS DEL CORDERO (ALELUYA)' },
      { id: 'alabanza16', title: 'YO QUIERO ENTRAR EN LA PRECENSIA DEL SE;OR (CRISTO NOMBRE SIN IGUAL)' },
      { id: 'alabanza17', title: 'DULCE ADORACION' },
      { id: 'alabanza18', title: 'CRISTO YO TE AMO' },
      { id: 'alabanza19', title: 'CRISTO QUIERO CAMINAR SIEMPRE CONTIGO' },
      { id: 'alabanza20', title: 'PODEROSO DIOS' },
      { id: 'alabanza21', title: 'MERECES LA GLORIA (CREO EN TI)' },
      { id: 'alabanza22', title: 'DIOS MANDA LLUVIA' },
      { id: 'alabanza23', title: 'DAME MAS DE TI (VENGO A TI)' },
      { id: 'alabanza24', title: 'DIOS EL MAS GRANDE Y DIGNO DE ALABAR' },
      { id: 'alabanza25', title: 'EL VIVE HOY (DIOS NOS ENVIO)' },
      { id: 'alabanza26', title: 'DIOS GRANDE ES TU AMOR' },
      { id: 'alabanza27', title: 'DIOS GRANDE ES TU AMOR' },
      { id: 'alabanza28', title: 'DIGNO Y SANTO' },
      { id: 'alabanza29', title: 'EN TU PRESENCIA' },
      { id: 'alabanza30', title: 'DAME UN NUEVO AMOR' },
      { id: 'alabanza31', title: 'ESCONDEME BAJO TUS ALAS OTRA VEZ' },
      { id: 'alabanza32', title: 'COMO EL SIERVO BUSCA POR LAS AGUAS' },
      { id: 'alabanza33', title: 'GRACIAS' },
      { id: 'alabanza34', title: 'EL NO FALLARA' },
      { id: 'alabanza35', title: 'GRACIAS SENIOR POR LAS LUCHAS QUE EL MUNDO DA' },
      { id: 'alabanza36', title: 'ERES EL MAS PRECIOSO' },
      { id: 'alabanza37', title: 'FIDELIDAD (ES SU FORMA DE MIRAR)' },
      { id: 'alabanza38', title: 'EXQUISITA PRECENSIA' },
      { id: 'alabanza39', title: 'CUAN GRANDE ES DIOS (EL ESPLENDOR DE UN REY)' },
      { id: 'alabanza40', title: 'ESCUDRI;EMOS LOS CAMINOS' },
      { id: 'alabanza41', title: 'EXALTATE (AL BORDE DE TU GRAN TRONO)' },
      { id: 'alabanza42', title: 'ESPIRITU SANTO/ BIENVENIDO A ESTE LUGAR' },
      { id: 'alabanza43', title: 'EL SENIOR ES MI PASTOR' },
      { id: 'alabanza44', title: 'EL ES MI PAZ' },
      { id: 'alabanza45', title: 'EL ES LA MANO EN MI HOMBRO' },
      { id: 'alabanza46', title: 'EL ME LEVANTARA' },
      { id: 'alabanza47', title: 'EL GOZO DE MI VIDA' },
      { id: 'alabanza48', title: 'ERES REY DE LOS CIELOS' },
      { id: 'alabanza49', title: 'HOY QUIERO AGRADECERTE/ PADRE MIO' },
      { id: 'alabanza50', title: 'HERMOSO ERES TU' },
      { id: 'alabanza51', title: 'HAY MOMENTOS QUE LAS PALABRAS NO ALCANZAN' },
      { id: 'alabanza52', title: 'HAY MOMENTOS TAN ESPECIALES' },
      { id: 'alabanza53', title: 'HUMILLAME Y QUEBRANTAME' },
      { id: 'alabanza54', title: 'HAZME BRILLAR SENIOR' },
      { id: 'alabanza55', title: 'HAY UNA UNSION' },
      { id: 'alabanza56', title: 'HAZ DE MI UNA OFRENDA' },
      { id: 'alabanza57', title: 'LEVANTO MIS MANOS' },
      { id: 'alabanza58', title: 'LEBRE ES JESUCRISTO NOS HIZO LIBRES' },
      { id: 'alabanza59', title: 'MI PRIMER AMOR' },
      { id: 'alabanza60', title: 'MIL GRACIAS' },
      { id: 'alabanza61', title: 'NO BASTA', source: alabanza61Raw },
      { id: 'alabanza62', title: 'NO DARE MI VIDA A NADIE', source: alabanza62Raw },
      { id: 'alabanza63', title: 'NO HAY NADIE COMO TU', source: alabanza63Raw },
      { id: 'alabanza64', title: 'ERES DIGNO DE ABRIR', source: alabanza64Raw },
      { id: 'alabanza65', title: 'MARAVILLADO ESTOY', source: alabanza65Raw },
      { id: 'alabanza66', title: 'GRACIAS SE;OR JESUS', source: alabanza66Raw },
      { id: 'alabanza67', title: 'OH ALMA MIA', source: alabanza67Raw },
      { id: 'alabanza68', title: 'OVEJA DE TU PRADO' },
      { id: 'alabanza69', title: 'OH BONDAD TAN INFINITA' },
      { id: 'alabanza70', title: 'PADRE DE LUZ' },
      { id: 'alabanza71', title: 'PORQUE SIEMPRE QUE YO TE BUSCO' },
      { id: 'alabanza72', title: 'PADRE CELESTIAL (MENESTEROSO)' },
      { id: 'alabanza73', title: 'QUIERO LEVANTAR MIS MANOS (HIJO DE DIOS)' },
      { id: 'alabanza74', title: 'QUIERO ESTAR EN TU PRECENSIA' },
      { id: 'alabanza75', title: 'QUIEN ERA YO' },
      { id: 'alabanza76', title: 'QUE LINDO ES MI CRISTO' },
      { id: 'alabanza77', title: 'QUIERO LLENAR TU TRONO DE ALABANZA' },
      { id: 'alabanza78', title: 'RESUCITO' },
      { id: 'alabanza79', title: 'RENUEVAME' },
      { id: 'alabanza80', title: 'SOBERANO DIOS' },
      { id: 'alabanza81', title: 'SE;OR AQUI ESTA MI VIDA' },
      { id: 'alabanza82', title: 'SALMOS 40' },
      { id: 'alabanza83', title: 'SANGRE QUE ME DA LA PAZ' },
      { id: 'alabanza84', title: 'SI ALGUNA VEZ' },
      { id: 'alabanza85', title: 'SE;OR ERES GRANDE' },
      { id: 'alabanza86', title: 'CUAN PRECIOSAS SON TUS MISERICORDIAS' },
      { id: 'alabanza87', title: 'JEHOVA ES LA FORTALEZA DE MI VIDA' },
      { id: 'alabanza88', title: 'SENDAS DIOS HARA' },
      { id: 'alabanza89', title: 'SOBRE TODO' },
      { id: 'alabanza90', title: 'SENTADO EN SU TRONO' },
      { id: 'alabanza91', title: 'TE ALABO MI SE;OR TE ALABO' },
      { id: 'alabanza92', title: 'TU ERES MI CIELO' },
      { id: 'alabanza93', title: 'TU RIO FLUIRA' },
      { id: 'alabanza94', title: 'TU ME HACES TAN FELIZ' },
      { id: 'alabanza95', title: 'SALMOS 145 TE EXALTARE' },
      { id: 'alabanza96', title: 'TU AMOR ES TAN PURO' },
      { id: 'alabanza97', title: 'TU FIDELIDAD/COMO EL SIERVO' },
      { id: 'alabanza98', title: 'TU MISERICORDIA' },
      { id: 'alabanza99', title: 'TEMPRANO YO TE BUSCARE' },
      { id: 'alabanza100', title: 'TE AMO REY' },
      { id: 'alabanza101', title: 'TENGO UN PERFUME' },
      { id: 'alabanza102', title: 'ERES TU EL CREADOR (VENIMOS)' },
      { id: 'alabanza103', title: 'YO POR MEDIO DE TI' },
      { id: 'alabanza104', title: 'YO SOY FELIZ EN EL' },
      { id: 'alabanza105', title: 'VUELVE' },
      { id: 'alabanza106', title: 'YO QUIERO MAS DE TI' },
      { id: 'alabanza107', title: 'ERES MI RESPIRAR' },
      { id: 'alabanza108', title: 'DIOS IMPARABLE' },
      { id: 'alabanza109', title: 'PODEROSO DIOS' },
      { id: 'alabanza110', title: 'TE ADORO A TI' },
      { id: 'alabanza111', title: 'ME HAS QUEBRANTADO' },
      { id: 'alabanza112', title: 'TE AMO REY' },
      { id: 'alabanza113', title: 'TENGO UN PERFUME' },
      { id: 'alabanza114', title: 'ERES TU EL CREADOR (VENIMOS)' },
      { id: 'alabanza115', title: 'YO POR MEDIO DE TI' }
    ]
  },
  {
    id: 'avivamiento',
    name: 'Avivamiento',
    description: 'Cantos para celebrar con gozo',
    hymns: [
      { id: 'avivamiento1', title: 'MIRA CUAN BUENO', source: '' },
      { id: 'avivamiento2', title: 'GLORIA Y PODER', source: '' },
      { id: 'avivamiento3', title: 'BUENO ES ALABARTE OH DIOS', source: alabanza1Raw },
      { id: 'avivamiento4', title: 'TODOS UNIDOS A UNA VOZ', source: '' },
      { id: 'avivamiento5', title: 'HAY PODER EN JESÚS', source: '' }
    ]
  },
  {
    id: 'servicio',
    name: 'Programa de servicio',
    description: 'Participaciones y orden del servicio',
    hymns: [
      { id: 'servicio1', title: 'Cantar alabanzas de avivamiento' },
      { id: 'servicio2', title: 'Pasar al hermano encargado a dar testimonio' },
      { id: 'servicio3', title: 'Continuar con el programa de servicio' }
    ]
  }
];

export const allHymns = categories.flatMap((category) =>
  category.hymns.map((hymn) => ({ ...hymn, category: category.name }))
);
