create table if not exists public.hymns (
  id bigint generated by default as identity primary key,
  number integer not null,
  title text not null,
  lyrics text not null default '',
  category text not null check (category in ('adoracion', 'avivamiento')),
  created_at timestamptz not null default now()
);

create table if not exists public.service_program (
  id bigint generated by default as identity primary key,
  service_date date not null default current_date,
  step_number integer not null,
  description text not null,
  created_at timestamptz not null default now()
);

alter table public.hymns enable row level security;
alter table public.service_program enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'hymns' and policyname = 'Public can read hymns') then
    create policy "Public can read hymns" on public.hymns for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'service_program' and policyname = 'Public can read service program') then
    create policy "Public can read service program" on public.service_program for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'hymns' and policyname = 'Authenticated users manage hymns') then
    create policy "Authenticated users manage hymns" on public.hymns for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'service_program' and policyname = 'Authenticated users manage service program') then
    create policy "Authenticated users manage service program" on public.service_program for all to authenticated using (true) with check (true);
  end if;
end $$;

create index if not exists hymns_category_number_idx on public.hymns(category, number);
create index if not exists service_program_date_step_idx on public.service_program(service_date, step_number);
